// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfquqfyfihsefvngxuit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmcXVxZnlmaWhzZWZ2bmd4dWl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwODE5MTUsImV4cCI6MjA1NTY1NzkxNX0.sEtTddw0ZDhZNqmu5WrgLr-hi0gmSw7QXVLiqlcD4DY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);